name: sneakerx
description: A Sneaker Shopping App.

publish_to: 'none'

version: 3.2.1+3

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  provider: ^6.1.1
  url_launcher: ^6.2.2
  image_picker: ^1.0.5
  numberpicker: ^2.1.2
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/fonts/

  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/futura.ttf
        - asset: assets/fonts/futura_bold.ttf
          weight: 700

