// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGfBmo-0Qc2Qkx3uTUu-m8Jjd9B_84yF8',
    appId: '1:255539310592:web:6479ebd6907122779b28e5',
    messagingSenderId: '255539310592',
    projectId: 'sneakerx-28e9d',
    authDomain: 'sneakerx-28e9d.firebaseapp.com',
    storageBucket: 'sneakerx-28e9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe9tXeiDl2N8jguawEuTAesFGZZ4g3Lyc',
    appId: '1:255539310592:android:130e0a91cedb666e9b28e5',
    messagingSenderId: '255539310592',
    projectId: 'sneakerx-28e9d',
    storageBucket: 'sneakerx-28e9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVWnygHG83ani7G-QjaOKvswEECbuB4EQ',
    appId: '1:255539310592:ios:5e521a764449a6529b28e5',
    messagingSenderId: '255539310592',
    projectId: 'sneakerx-28e9d',
    storageBucket: 'sneakerx-28e9d.appspot.com',
    androidClientId:
        '255539310592-aqrimrujt3nbv01t7n40fioa7ouu4o6a.apps.googleusercontent.com',
    iosClientId:
        '255539310592-r4in6p9drgu0uhvjhsfnh82hcuc7suth.apps.googleusercontent.com',
    iosBundleId: 'com.aditya.sneakerx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVWnygHG83ani7G-QjaOKvswEECbuB4EQ',
    appId: '1:255539310592:ios:5e521a764449a6529b28e5',
    messagingSenderId: '255539310592',
    projectId: 'sneakerx-28e9d',
    storageBucket: 'sneakerx-28e9d.appspot.com',
    androidClientId:
        '255539310592-aqrimrujt3nbv01t7n40fioa7ouu4o6a.apps.googleusercontent.com',
    iosClientId:
        '255539310592-r4in6p9drgu0uhvjhsfnh82hcuc7suth.apps.googleusercontent.com',
    iosBundleId: 'com.aditya.sneakerx',
  );
}
